BINDIR = ./
EXECUTABLE	:= template

CUFILES := template.cu
CU_DEPS := template_kernel.cu
CCFILES := template_gold.cpp 

ROOTDIR := /Developer/GPU\ Computing/C/common

include $(ROOTDIR)/../common/common.mk