BINDIR = ./
EXECUTABLE := wigner.bin

DIRS := cudahelpers
CCFILES := wigner.cpp misc.cpp
CUFILES := wigner.cu batchfft.cu spectre.cu

USECUFFT := 1
USEGLUT := 1
USEGLLIB := 1

ROOTDIR := /Developer/GPU\ Computing/C/common

include $(ROOTDIR)/../common/common.mk
